# Use an official PostgreSQL image as the base image
FROM postgres:latest

# Set the POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1049
ENV POSTGRES_DB=rungroopcourse

# Expose the default PostgreSQL port
EXPOSE 5432
